### PR TITLE
Use full path as Type for unnamed types

### PR DESCRIPTION
**Pull request by MnlPhlp**
I had a lot of problems with larger structs with many fields leading to duplicate type names.
This PR changes the generated type names to use the full path to the field with struct name, field name etc. to create a unique type name.

This makes the type names longer but prevents collisions.

If there are any reasons why someone would want this to not be the case, i could add some feature guards and make this optional.

### CODE REVIEW

**Comment by jcaesar** [comment]
Thank you for the PR. I do think this should be optional. Mostly because this a breaking change (sorry for you having to change all the tests), but also because if you only have a handful of collisions, you can just override the names in-place `struct A { a: struct AA {} }`, and I'd like to avoid java style FooBarCreatorFactoryPattern long names.

For syntax, maybe you or I can add something like `strike! { #[structstruck::names_from_path] … }`.
(I think that naming scheme would also make sense with #10, and I think I want to rename `strikethrough` to fit into that scheme, too.)

PS: As it currently is, it would need updating the docs in `src/lib.rs` too.

**Comment by MnlPhlp** [comment]
Do you think it is better to have this as an option per struct? Another way would be to make this a crate feature. In that case the user can decide once in the cargo.toml what names they want.
```toml
structstruck = { .., features = ["pathnames"]}
```

**Comment by jcaesar** [comment]
Features aren't a good idea here due to [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification). (And in any case, features shouldn't change functionality, they should be purely additive.)

I'd say option as attribute per struct is nice, but we could have different macro names like `structstruct::strike!{…}` vs `structstruck::flatten_with_ancestry!{…}` or something. (In case you haven't noticed, I'm bad at coming up with sane names…)

**Comment by MnlPhlp** [comment]
I think i like the syntax of an additional attrubute the most
```
strike! { #[structstruck::names_from_path] … }
```
Will look into implementing that in the next few days

**Comment by MnlPhlp** [comment]
@jcaesar I made the modifications and added some tests with a path variant.
All esisting tets pass without changes.

The only thing that changed without the attribute is naming of multiple structs in a tuple.
Every struct after the first one gets a number appended.
I don't think this is a backwards compatibility problem. Before the change, two types were created with the same name, resulting in a compile error.
See test `two_tuple_values`

Let me know if there is anything else that I should change

**Comment by jcaesar** [comment]
Okay, I had a look, and ended up messing with it quite heavily.

* I renamed `strikethrough` to `structstruck::each`
* I renamed `structstruck::name_from_path` to `long_names` and made it apply only to the current struct.
* To get the effect of `name_from_path`, you'll now need `#[structstruck::each[structstruck::long_names]]` - is that too awkward? Any good alias to add?
* On the implementation side, I changed the mutable vector (I still don't get how that actually worked, since you did end up clearing it in the middle without restoring it later? ) to an immutable bunch of references. The vector should have never been longer than 3, if I understand correctly. 
* Two more tests
* Beta publish

**Comment by MnlPhlp** [comment]
The implementation was probably more complicated than it needed to be so thanks for the changes.
> To get the effect of name_from_path, you'll now need #[structstruck::each[structstruck::long_names]] - is that too awkward? Any good alias to add?

I actually quite like the approach. I seems consistent with what structstruck::each should do.
If you want to make it easier maybe you could add an alias like `#[structstruck::long_names_each]` or something but I don't think that is needed.

**Pull request merged**
